name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call:
    inputs:
      prebuild_command: "apt install jemalloc"


jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift.org"
      python_lint_check_enabled: false

